### ISSUE TITLE
Clean COM_Log

### ISSUE THREAD

**Issue by oherrou** [micapat/Krystal#14]
Edit : Voir plus bas

**Comment by oherrou** [comment]
Mise à jour de l'écriture des logs de débugs sur la mémoire. Le numéro de la  ligne apparaît avant de donné le nom du fichier pour éviter d'avoir trop \n.
Il faut utiliser COM_LOG_DEBUG uniquement pour lorsque l'on a besoin d'information sur la mémoire.
Ajout du répertoire logs/

**Comment by micapat** [comment]
Done.
