### ISSUE TITLE
SDL_Sound & SDL_Music

### ISSUE THREAD

**Issue by micapat** [micapat/Krystal#28]
Global variable to handle the volume of the musics/sounds for the options.

**Comment by oherrou** [comment]
Musics will always be played at the volume defined by the global variable SDL_Music_Volume.
Sounds will be played at the volume defined  by the function "void SDL_Sound_Play(x, y, Uint32 iVolume, z) "  multiplied by a percentage defined by the global variable SDL_Sound_Volume.

**Comment by micapat** [comment]
Indeed. Some remarks:

- Global variables must be static to the source file, NEVER in an include!
- Global variables name must have the format "<MODULE>_<SUBMODULE>_lowerCamelCase", so for example "SDL_Sound_volume".
- Is there a constant for the value "128" for the music volume?

SDL_Sound_Play( )
No cast are needed for iVolume if the operator precedence is respected --> (( a * b ) / 100 ).

SDL_Sound_SetVolume( )
You can use directly the global variable for the logs.

SDL_Music_SetVolume( )
No cast are needed for SDL_Music_Volume if the operator precedence is respected --> (( a * b ) / 100 ).

I don't know, but maybe for SDL_Music_Play( ), the volume must be passed as parameter (Not all our musics will have the same volume)?

:+1:

**Comment by oherrou** [comment]
Fixed

**Comment by micapat** [comment]
Closed.
